config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  devise_for :users
  
  get 'c_:id', to: 'categories#show', as: :category

  resources :articles do
     resources :comments
     resources :barrages
   end

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :category
	belongs_to :user
	has_many :comments
	has_many :barrages
	mount_uploader :avatar, AvatarUploader

	validates :title, :remark, :category_id, :source, :vid, presence: true
	validates :title, length: { maximum: 50 }
	validates :remark, length: { maximum: 200 }
	validates :category_id, inclusion: { in: [1, 2, 3], message: "分类不存在" }
	validates :source, inclusion: { in:  ["youku", "sina", "qq"], message: "您所选择的视频源暂不支持" }
	validates :title, :vid, uniqueness: true

end

app/models/barrage.rb
class Barrage < ActiveRecord::Base
	belongs_to :user
	belongs_to :article
	validates :content, presence: true
	validates :time, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :article
	belongs_to :user
	validates :text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :articles
         has_many :comments
         has_many :barrages
         mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	protected
		def configure_permitted_parameters
			devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(:email, :password, :username, :userbrief, :avatar) }
		end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]
  def index
        @articles_hot = Article.all.order("count DESC").limit(12)

        @categories = Category.all

  end

  def show
  	@article = Article.find(params[:id])
        @barrage = Barrage.new
        @comment = Comment.new
        @comments = @article.comments.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10 )

  end

  def new
  	@article = Article.new
        @user = current_user
  end

  def create
  	@article = current_user.articles.build(article_params)
        if @article && @article.save
  	       redirect_to article_path(@article)
        else
              render 'new'
        end
  end

  private
  	def article_params
  		params.require(:article).permit(:avatar, :title, :remark, :category_id, :source, :vid)
  	end
end

app/controllers/barrages_controller.rb
class BarragesController < ApplicationController
  def create
  	@article = Article.find(params[:article_id])
  	@barrage = current_user.barrages.build(barrage_params)
  	@barrage.article = @article
  	respond_to do |format|
	        	if @barrage && @barrage.save
	        		format.html { redirect_to @article }
	                        	format.js {}
	                       	format.json { render json: @barrage, status: :created, location: @barrage }
	        	else
	        		format.html { redirect_to @article }
	                        	format.json { render json: @barrage.errors, status: :unprocessable_entity }
	        	end
       	end
  end

  private 
  	def barrage_params
  		params.require(:barrage).permit(:time, :content, :article_id)
  	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  	@category = Category.find(params[:id])
  	@articles = @category.articles.order('created_at DESC').paginate(:page => params[:page], :per_page => 20 )
  	@articles_hot = @category.articles.order('count DESC').limit(10)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
  	@article = Article.find(params[:article_id])
  	@comment = current_user.comments.build(comment_params)
  	@comment.article = @article
        respond_to do |format|
        	if @comment && @comment.save
        		format.html { redirect_to @article }
                        format.js {}
                        format.json { render json: @comment, status: :created, location: @comment }
        	else
        		format.html { redirect_to @article }
                        format.json { render json: @comment.errors, status: :unprocessable_entity }
        	end
        end
  end

  def delete
  end

  private 
  	def comment_params
  		params.require(:comment).permit(:text, :article_id)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def categories
		@categories = Category.all
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_c(category)
		@article_c = category.articles.order("created_at DESC").limit(12)
	end

	def article_c_hot(category)
		@article_c_hot = category.articles.order("count DESC").limit(10)
	end
end

app/helpers/barrages_helper.rb
module BarragesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_articles_hot_item.html.erb
<%= link_to image_tag(article.avatar.article_thumb, size: "135x100"), article_path(article) %>
<%= link_to article.title, article_path(article) %>
<div class="article-stat">
	<span class="glyphicon glyphicon-expand"></span> <%= article.count %> <span class="glyphicon glyphicon-star"></span> <%= article.favout_count %>
</div>

app/views/articles/index.html.erb
<% if @articles_hot.any? %>
<div class="row">
	<div class="col-md-4 col-xs-6">
		<div class="carousel slide" id="main-carousel" data-ride="carousel">
			<ol class="carousel-indicators">
				<li class="active" data-target="#main-carousel" data-slide-to="0"></li>
				<li data-target="#main-carousel" data-slide-to="1"></li>
				<li data-target="#main-carousel" data-slide-to="2"></li>
				<li data-target="#main-carousel" data-slide-to="3"></li>
			</ol>

			<!-- Wrapper for slides -->
			<div class="carousel-inner" role="listbox">
				<% @articles_hot[0..3].each do |article_hot| %>
					<% if article_hot == @articles_hot.first %>
						<div class="item active">
					<% else %>
						<div class="item">
					<% end %>
							<%= link_to image_tag(article_hot.avatar.article_thumb, size: "360x270"), article_path(article_hot) %>
							<div class="carousel-caption">
								<h4><%= article_hot.title %></h4>
							</div>
						</div>
				<% end %>
			</div>
		</div>
	</div>
	<div class="col-md-8 col-xs-6">
		<% @articles_hot[4..11].each do |article_hot| %>
			<div class="col-md-3 col-xs-6 index-item">
				<%= link_to image_tag(article_hot.avatar.article_thumb, size: "165x120"), article_path(article_hot), title: article_hot.title %>
			</div>
		<% end %>
	</div>
</div>
<% end %>

<% @categories.each do |category| %>
	<div class="row">
		<div class="col-md-9">
			<div class="index-category-title page-header">
				<h3>
					<%= link_to category_path(category) do %>
						<%= category.name %> <small>更多内容</small>
					<% end %>

				</h3>
			</div>
			<% article_c(category).each do |article| %>
				<div class="article-hot-item col-md-2">
					<%= render partial: 'articles_hot_item', locals: { article: article } %>
				</div>
			<% end %>
		</div>
		<div class="col-md-3">
			<div class="index-category-title page-header">
				<h3><%= link_to "本区热门", category_path(category) %></h3>
			</div>
			<div class="index-hot-list">
				<% n = 0 %>
				<% article_c_hot(category).each do |article| %>
					<div class="index-hot-list-item">
						<span class="label label-default"><%= n + 1 %></span> <%= link_to article.title, article_path(article) %>
						<% n += 1 %>
					</div>	
				<% end %>
			</div>
		</div>
	</div>
<% end %>

app/views/articles/new.html.erb
<div class="row" id="upload-article">
	<div class="col-md-4">
		<div class="user-info">
			<div class="page-header"><h3>用户</h3></div>
			<div><%= image_tag @user.avatar.user_thumb, size: "100x100" %></div>
			<h4><%=link_to @user.username, "#" %></h4>
			<div>
				<p>投稿统计：<%= @user.articles.count %></p>
				<p>邮箱：<br><%= @user.email %></p>
				<p>注册时间：<br> <%= @user.created_at %></p>
				<p><%= link_to "登出", destroy_user_session_path, method: :delete %></p>
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="upload">
			<div class="page-header"><h3>投稿</h3></div>
			<%= form_for @article, html: { class: "form-horizontal", role: "form" } do |f| %>
				<% if @article.errors.any? %>
					<ul class="list-group">
						<% @article.errors.full_messages.each do |error| %>
							<li class="list-group-item list-group-item-danger"><%= error %></li>
						<% end %>
					</ul>
				<% end %>
				<div class="form-group">
					<%= f.label :avatar, "封面图片:", class: "control-label col-md-2" %>
					<div class="col-md-10">
						<%= f.file_field :avatar, class: "form-control" %>
						<%= f.hidden_field :avatar_cache %>
					</div>
				</div>
				<div class="form-group">
					<%= f.label :title, "标题:", class: "control-label col-md-2" %>
					<div class="col-md-10">
						<%= f.text_field :title, class: "form-control" %>
					</div>
				</div>
				<div class="form-group">
					<%= f.label :remark, "备注:", class: "control-label col-md-2" %>
					<div class="col-md-10">
						<%= f.text_area :remark, size: "100x4", class: "form-control" %>
					</div>
				</div>
				<div class="form-group">
					<%= f.label :category_id, "分类:", class: "control-label col-md-2" %>
					<div class="col-md-4">
						<%= f.select :category_id, options_for_select([['电影', 1], ['电视', 2], ['综艺', 3]]) %>
					</div>
				</div>	
				<div class="form-group">
					<%= f.label :source, "来源:", class: "control-label col-md-2" %>
					<div class="col-md-10">
						<label class="radio-inline">
							<%= f.radio_button :source, "youku" %>优酷
						</label>
						<label class="radio-inline">
							<%= f.radio_button :source, "sina" %>新浪
						</label>
						<label class="radio-inline">
							<%= f.radio_button :source, "qq" %>腾讯
						</label>
					</div>
				</div>
				<div class="form-group">
					<%= f.label :vid, "视频vid:", class: "control-label col-md-2" %>
					<div class="col-md-10">
						<%= f.text_field :vid, class: "form-control" %>
					</div>
				</div>

					<%= f.submit "提交", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/articles/show.html.erb
<div class="row ">
	<div class="col-md-9">
		<div class="article-show-stat">
			<div class="title"><%= @article.title %></div>
			<div class="nav">
				<%= link_to "首页", root_path %>/
				<%= link_to @article.category.name, category_path(@article.category) %>
				<%= @article.created_at.strftime("%Y-%m-%d %H:%M") %>
				<span class="glyphicon glyphicon-stats" title="播放"></span>
				<%= @article.count %> 
				<span class="glyphicon glyphicon-star" title="赞"></span>
				<%= @article.favout_count %>
			</div>
		</div>
	</div>
	<div class="col-md-3">
		<div class="article-show-user">
			<div class="user-img">
				<%= image_tag @article.user.avatar.user_thumb %>
			</div>
			<div class="user-name">
				<%= link_to @article.user.username %>
				<a href="#" class="btn btn-primary btn-xs" id="focuson"> 关注 </a>
			</div>
			<div class="user-brief">
				<%= @article.user.userbrief[0..50] %>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-9">
		<div class="player">
			<div id="youkuplayer" style="width:845px;height:522px"></div>
		</div>
	</div>
	<div class="col-md-3">
		<div class="barrages-table">
			<table class="table">
	  			<thead>
	  				<tr>
	  					<th>进度</th>
	  					<th>内容</th>
	  					<th>发送时间</th>
	  				</tr>
	  			</thead>
	  			<tbody id="barrages-list">
	  				<% if @article.barrages.any? %>
	  					<% @article.barrages.each do |barrage| %>
			  				<%= render barrage %>
			  			<% end %>
		  			<% end %>
	  			</tbody>
			</table>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-9">
		<div class="send-barrage">
			<%= form_for @barrage, remote: true, url: article_barrages_path(@article.id), html: { class: "form-inline" } do |f| %>
				<div class="form-group">
					<%= f.text_field :content, class: "form-control", id: "barrage-content", disabled: true %>
					<%= f.submit "发送弹幕", class: "btn btn-default", id: "barrage-submit" %>
					<%= f.hidden_field :time, id: "barrage-time" %>
				</div>
			<% end %>
		</div>
	</div>
	<div class="col-md-3">
		<div class="btn btn-default">
			<a href="#">分享</a>
		</div>
		<div class="btn btn-default"><span class="glyphicon glyphicon-thumbs-up"></span><a href="#">赞</a></div>
	</div>
</div>

<div class="row">
	<div class="col-md-9">
		<div class="article-show-remark">
			<%= @article.remark %>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-9">
		<div class="article-show-comment">
			<% if signed_in? %>
				<%= form_for @comment, remote: true, url: article_comments_path(@article.id) do |f| %>
					<div class="user-img">
						<%= image_tag current_user.avatar.user_thumb %>
					</div>
					<div class="form-group">
						<%= f.text_area :text, size: "85x4", class: "form-control" %>
						<%= f.submit "发布评论", class: "btn btn-primary btn-sm", id: "commit" %>
					</div>
				<% end %>
			<% end %>
			<div class="clear"></div>
		</div>
		<div id="article-show-comments-list">
			<% if @comments.any? %>
				<% @comments.each do |comment| %>
						<%= render comment %>
				<% end %>
			<% end %>
			<%= will_paginate @comments, renderer: BootstrapPagination::Rails %>
		</div>
	</div>
</div>

<script type="text/javascript">
player = new YKU.Player('youkuplayer',{
	styleid: '0',
	client_id: '4709a18f3ad1febf',
	vid: '<%= @article.vid %>',
	events:{
		onPlayerReady: function(){ /*your code*/ },
		onPlayStart: function(){ 
			
		 },
		onPlayEnd: function(){ 
			
		}
	}
});
function currentTime(){
	return player.currentTime();
};
</script>

app/views/barrages/_barrage.html.erb
<tr>
	<td><%= Time.at(barrage.time.to_i).strftime "%M:%S" %></td>
	<td><%= barrage.content %></td>
	<td><%= barrage.created_at.strftime('%m-%d %H:%M').to_s %></td>
</tr>

app/views/barrages/create.html.erb
<h1>Barrages#create</h1>
<p>Find me in app/views/barrages/create.html.erb</p>

app/views/barrages/create.js.erb
$("<%= j(render @barrage) %>").fadeIn("slow").appendTo("#barrages-list");
$("#barrage-content").val("");

app/views/categories/_article.html.erb
<div class="category-item-img col-md-4">
	<%= image_tag article.avatar.article_thumb.url, size: "120x75" %>
</div>
<div class="category-item-right col-md-8">
	<div class="title">
		<%= link_to article.title, article_path(article) %>
	</div>
	<div class="stat">
		<span class="glyphicon glyphicon-stats"></span> <%= article.count %>
		<span class="glyphicon glyphicon-star"></span> <%= article.favout_count %>
	</div>
	<div class="author">
		<span class="glyphicon glyphicon-user"></span> <%= link_to article.user.username %>
	</div>
</div>

<div class="info col-md-12">
	<%= article.remark[0..60] %>
</div>

app/views/categories/show.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="category-header">
			<div class="category-title"><%= @category.name %></div>
			<div class="category-tab">
				<a href="#" class="tab-i">拼音排序</a>/
				<a href="#" class="tab-i">投稿时间排序</a>/
				<a href="#" class="tab-i">视频热度排序</a>
			</div>
			<div class="clear"></div>
		</div>
		
			<% @articles.each do |article| %>
				<div class="category-items col-md-6">
					<div class="category-item">
						<%= render partial: 'categories/article', object: article %>
						<div class="clear"></div>
					</div>
					
				</div>
			<% end %>
			<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
		
	</div>
	<div class="col-md-3">
		<div class="category-header">
			<h4>本区热门</h4>
		</div>
		<div class="index-hot-list">
			<% n = 0 %>
			<% @articles_hot.each do |article_hot| %>
				<div class="index-hot-list-item">
					<span class="label label-default"><%= n+1 %></span> <%= link_to article_hot.title, article_path(article_hot) %>
					<% n += 1 %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/comments/_comment.html.erb
<div class="comments-list-item">
	<div class="user-img">
		<%= image_tag comment.user.avatar.user_thumb %>
		<p><%= link_to comment.user.username %></p>
	</div>
	<div class="comment">
		<%= comment.text %>
	</div>
	<div class="clear"></div>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/create.js.erb
$("<%= j(render @comment) %>").fadeIn("slow").prependTo("#article-show-comments-list");
$("#comment_text").val("");

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="footer-items row">
		<div class="footer-item col-md-4">
			<%= link_to "关于我们", "#" %>
		</div>
		<div class="footer-item col-md-4">
			<%= link_to "@Github", "https://github.com/cloudy9101/dodotv" %>
		</div>
		<div class="footer-item col-md-4">
			友情链接
		</div>
	</ul>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-nav">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "dodoTV", root_path, class: "navbar-brand" %>
		</div>

		<div class="collapse navbar-collapse" id="header-nav">
			<ul class="nav navbar-nav">
				<li class="active"><%= link_to "首页", root_path %></li>
				<% categories.each do |category| %>
					<li><%= link_to category.name, category_path(category) %></li>
				<% end %>
				<li><a href="#">排行榜</a></li>
			</ul>

			<form class="navbar-form navbar-right" role="search">
				<div class="form-group">
					<input type="text" placeholder="Search" class="form-control">
				</div>
				<button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <%= current_user.username %><span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu" >
							<li>
								<%= link_to new_article_path do %>
									<span class="glyphicon glyphicon-cloud-upload"></span> 投稿
								<% end %>
							</li>
							<li><%= link_to "设置", edit_user_registration_path %></li>
							<li><%= link_to "登出", destroy_user_session_path, method: :delete %></li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "注册", new_user_registration_path %></li>
					<li><%= link_to "登陆", new_user_session_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-cn">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
 	<title>Dodotv</title>
 	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 	<script type="text/javascript" src="http://player.youku.com/jsapi"></script>
 	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">

		<%= render 'layouts/header' %>
	
		<%if !(notice.nil? || alert.nil?) %>
			<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
		<% end %>
		
		<%= yield %>

		<%= render 'layouts/footer' %>

	</div>	
</body>
</html>